"use client";
import { Suspense, useState } from "react";
import { useSearchParams } from "next/navigation";
import { motion } from "framer-motion";
import { Bell, Menu, Search, Plus, ArrowUpRight, CalendarDays, FileText, Megaphone, Settings2, ShieldCheck, Upload, UsersRound, Wallet, Wrench, ScanFace, BarChart3 } from "lucide-react";
import Sidebar from "@/components/Sidebar";
import ThemeToggle from "@/components/ThemeToggle";
import Kpi from "@/components/Kpi";
import { ROLES, type RoleKey, type ModuleKey } from "@/lib/data";

type Direction = "up" | "down" | "flat";
type Stat = [string, string, string, Direction];
const notices = [["Annual General Meeting", "20 July, 6 PM · Clubhouse", "Notice", "2h ago"], ["Water supply suspended", "11 AM–2 PM today", "Emergency", "5h ago"], ["Independence Day celebration", "15 August · Central lawn", "Event", "1d ago"]];
const residents = [["Rahul Shah", "A-1204", "Owner", "Active", "Nil"], ["Ramesh Iyer", "A-0501", "Owner", "Active", "Nil"], ["Sana Qureshi", "B-0710", "Tenant", "Active", "₹4,500"], ["George Thomas", "C-1108", "Tenant", "Notice", "₹9,000"]];
const bills = [["INV-2607-1204", "A-1204", "₹6,800", "Paid"], ["INV-2607-0710", "B-0710", "₹4,500", "Overdue"], ["INV-2607-1108", "C-1108", "₹9,000", "Overdue"], ["INV-2607-1101", "D-1101", "₹6,800", "Pending"]];
const complaints = [["Water leakage in A-wing parking", "Plumbing", "High", "Open"], ["Lift 2 tripping in B-wing", "Electrical", "Urgent", "Open"], ["Garbage not collected C-wing", "Housekeeping", "Medium", "In progress"], ["Garden lights out near clubhouse", "Common Area", "Medium", "Resolved"]];
const visitors = [["Amazon Delivery", "Delivery", "A-1204", "6:42 PM", "Inside"], ["Dr. S. Kapoor", "Guest", "C-0304", "6:20 PM", "Inside"], ["Uber MH04 KT8890", "Cab", "B-0902", "6:05 PM", "Exited"], ["Unknown Guest", "Guest", "B-0710", "6:50 PM", "Waiting"]];

function Badge({ children }: { children: string }) { const s = children.toLowerCase(); const tone = s.includes("paid") || s.includes("active") || s.includes("inside") || s.includes("resolved") ? "text-[var(--good)] bg-emerald-500/10" : s.includes("overdue") || s.includes("urgent") || s.includes("notice") || s.includes("waiting") ? "text-[var(--bad)] bg-red-500/10" : s.includes("high") || s.includes("progress") ? "text-amber-600 bg-amber-500/10" : "text-ink-soft bg-surface-2"; return <span className={`inline-flex rounded-full px-2.5 py-1 text-[.7rem] font-bold ${tone}`}>{children}</span>; }
function Stats({ items }: { items: Stat[] }) { return <div className="grid grid-cols-2 gap-x-6 gap-y-7 xl:grid-cols-4">{items.map((x, i) => <Kpi key={x[0]} label={x[0]} value={x[1]} delta={x[2]} dir={x[3]} index={i} />)}</div>; }
function Section({ title, action, icon: Icon, children }: { title: string; action?: string; icon?: any; children: React.ReactNode }) { return <section className="border-t border-border pt-4"><div className="mb-5 flex items-center justify-between gap-4"><h2 className="flex items-center gap-2 text-[.75rem] font-bold uppercase tracking-[.12em] text-ink-faint">{Icon && <Icon size={16} className="text-primary" />}{title}</h2>{action && <button className="inline-flex items-center gap-1.5 text-sm font-semibold text-primary-strong hover:underline">{action}<ArrowUpRight size={14} /></button>}</div>{children}</section>; }
function Table({ kind }: { kind: "residents" | "billing" }) { const rows = kind === "residents" ? residents : bills; const heads = kind === "residents" ? ["Resident", "Flat", "Type", "Status", "Outstanding"] : ["Invoice", "Flat", "Amount", "Status"]; return <div className="overflow-x-auto rounded-xl border border-border"><table className="w-full min-w-[620px] text-left"><thead><tr className="bg-surface-2 text-[.68rem] font-bold uppercase tracking-[.1em] text-ink-faint">{heads.map(h => <th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i} className="border-t border-border hover:bg-surface-2/70">{row.map((x, j) => <td key={j} className={`px-4 py-3.5 text-sm ${j === 0 ? "font-semibold" : ""} ${x.startsWith("₹") ? "tabular-nums" : ""}`}>{(kind === "residents" && (j === 2 || j === 3)) || (kind === "billing" && j === 3) ? <Badge>{x}</Badge> : x}</td>)}</tr>)}</tbody></table></div>; }
function NoticeList() { return <div className="divide-y divide-border rounded-xl border border-border">{notices.map(x => <div key={x[0]} className="flex flex-wrap items-center justify-between gap-4 px-4 py-4 hover:bg-surface-2/60 sm:px-5"><div className="flex items-start gap-3"><span className="mt-0.5 grid h-8 w-8 place-items-center rounded-full bg-primary-tint text-primary-strong"><Megaphone size={15} /></span><div><div className="font-semibold">{x[0]}</div><div className="mt-1 text-sm text-ink-faint">{x[2]} · {x[1]}</div></div></div><span className="text-xs text-ink-faint">{x[3]}</span></div>)}</div>; }

function ModuleView({ mod }: { mod: ModuleKey }) {
  if (mod === "dashboard") return <div className="space-y-12"><Stats items={[["Collection this cycle", "₹2.84L", "92% collected", "up"], ["Outstanding dues", "₹1.57L", "6 flats pending", "down"], ["Open complaints", "8", "2 urgent", "flat"], ["Occupancy", "94%", "148 / 158 flats", "up"]]} /><Section title="Latest notices" action="View all" icon={Megaphone}><NoticeList /></Section><div className="grid gap-10 lg:grid-cols-[1.15fr_.85fr]"><Section title="Collection pulse" icon={BarChart3}><div className="rounded-xl border border-border bg-surface px-5 py-5"><div className="flex h-[130px] items-end gap-2">{[52, 65, 58, 76, 68, 88, 82, 96].map((h, i) => <div key={i} className="flex-1 rounded-t bg-primary/80 transition hover:bg-primary" style={{ height: `${h}%` }} />)}</div><div className="mt-4 flex justify-between text-xs text-ink-faint"><span>12 Jul</span><span>19 Jul</span></div></div></Section><Section title="Quick actions" icon={Plus}><div className="grid grid-cols-2 gap-3">{[["Create invoice", Wallet], ["Log visitor", ScanFace], ["Post notice", Megaphone], ["New request", Wrench]].map(([label, Icon]: any) => <button key={label} className="flex min-h-20 flex-col items-start justify-between rounded-xl border border-border bg-surface p-4 text-left transition hover:-translate-y-0.5 hover:bg-surface-2"><Icon size={18} className="text-primary" /><span className="text-sm font-semibold">{label}</span></button>)}</div></Section></div></div>;
  if (mod === "residents") return <div className="space-y-12"><Stats items={[["Total flats", "158", "4 blocks A–D", "flat"], ["Owners", "112", "71% of units", "flat"], ["Tenants", "36", "KYC verified", "up"], ["Vacant", "10", "6% of units", "down"]]} /><Section title="Resident directory" action="Export" icon={UsersRound}><Table kind="residents" /></Section></div>;
  if (mod === "billing") return <div className="space-y-12"><Stats items={[["Billed in July", "₹3.09L", "158 invoices", "flat"], ["Collected", "₹2.84L", "92%", "up"], ["Pending", "₹15.7K", "3 flats", "flat"], ["Overdue + late fee", "₹13.5K", "2 flats", "down"]]} /><Section title="Invoice register" action="Create invoice" icon={Wallet}><Table kind="billing" /></Section><Section title="Collection split" icon={BarChart3}><div className="grid gap-4 sm:grid-cols-3">{[["Maintenance", "₹2.10L", "74%"], ["Sinking fund", "₹48K", "17%"], ["Other charges", "₹26K", "9%"]].map(x => <div key={x[0]} className="rounded-xl border border-border p-4"><div className="text-sm text-ink-soft">{x[0]}</div><div className="mt-3 text-2xl font-semibold tabular-nums">{x[1]}</div><div className="mt-1 text-xs text-primary-strong">{x[2]} of collected</div></div>)}</div></Section></div>;
  if (mod === "visitors") return <div className="space-y-12"><Stats items={[["Entries today", "42", "+6", "up"], ["Inside now", "12", "3 deliveries", "flat"], ["Deliveries", "18", "peak 6–8 PM", "up"], ["Awaiting approval", "1", "B-0710", "flat"]]} /><Section title="Gate activity" action="Log visitor" icon={ScanFace}><div className="divide-y divide-border rounded-xl border border-border">{visitors.map(x => <div key={x[0]} className="flex flex-wrap items-center justify-between gap-4 px-4 py-4 hover:bg-surface-2/60 sm:px-5"><div><div className="font-semibold">{x[0]}</div><div className="mt-1 text-sm text-ink-faint">{x[1]} · {x[2]} · {x[3]}</div></div><Badge>{x[4]}</Badge></div>)}</div></Section><Section title="Today at the gate" icon={CalendarDays}><div className="rounded-xl border border-border p-5"><div className="flex h-3 overflow-hidden rounded-full bg-surface-2"><span className="w-[48%] bg-primary" /><span className="w-[27%] bg-primary/60" /><span className="w-[25%] bg-primary/30" /></div><div className="mt-3 flex justify-between text-xs text-ink-faint"><span>Morning 14</span><span>Afternoon 11</span><span>Evening 17</span></div></div></Section></div>;
  if (mod === "complaints") return <div className="space-y-12"><Stats items={[["Open", "2", "1 urgent", "flat"], ["In progress", "1", "within SLA", "flat"], ["Resolved in 7d", "5", "avg 1.2 days", "up"], ["Satisfaction", "4.6", "22 ratings", "up"]]} /><Section title="Service queue" action="New request" icon={Wrench}><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{["Open", "In progress", "Resolved", "Closed"].map(status => <div key={status} className="rounded-2xl bg-surface-2 p-3"><div className="mb-3 flex items-center justify-between px-1 text-sm font-semibold">{status}<span className="text-xs text-ink-faint">{complaints.filter(x => x[3] === status).length}</span></div>{complaints.filter(x => x[3] === status).map((x, i) => <div key={x[0]} className="mb-2 rounded-xl border border-border bg-surface p-3 transition hover:-translate-y-0.5"><div className="text-[.68rem] font-bold uppercase tracking-[.08em] text-ink-faint">{x[1]}</div><div className="my-2 text-sm font-semibold leading-5">{x[0]}</div><div className="flex items-center gap-2"><Badge>{x[2]}</Badge><span className="text-xs text-ink-faint">CMP-{341 - i}</span></div></div>)}</div>)}</div></Section></div>;
  const generic: Record<string, { stats: Stat[]; title: string; icon: any; rows: [string, string, string][] }> = {
    comms: { stats: [["Active notices", "5", "4 unread avg", "flat"], ["Upcoming events", "2", "64 RSVPs", "up"], ["Delivery rate", "98%", "in-app + email + SMS", "up"], ["Read rate", "81%", "last 30 days", "up"]], title: "Communication feed", icon: Megaphone, rows: [["Annual General Meeting", "Notice", "20 July, 6 PM"], ["Water supply suspended", "Emergency", "11 AM–2 PM today"], ["Independence Day celebration", "Event", "15 August · Central lawn"]] },
    finance: { stats: [["Income FY26", "₹34.2L", "+8% YoY", "up"], ["Expenses FY26", "₹28.8L", "+5% YoY", "down"], ["Net surplus", "₹5.4L", "healthy", "up"], ["Reserve fund", "₹18.4L", "corpus intact", "up"]], title: "General ledger", icon: Wallet, rows: [["Maintenance collection · July", "Income", "+₹2.84L"], ["Security agency · SecureGuard", "Expense", "−₹96K"], ["Common electricity · MSEB", "Expense", "−₹63.4K"], ["Lift AMC · OtisCare", "Expense", "−₹42K"]] },
    reports: { stats: [["Collection efficiency", "92%", "healthy", "up"], ["Complaint SLA", "88%", "on track", "up"], ["Occupancy", "94%", "148 / 158", "up"], ["Engagement", "81%", "last 30 days", "up"]], title: "Society health index", icon: BarChart3, rows: [["Collection efficiency", "92%", "Healthy"], ["Complaint SLA", "88%", "On track"], ["Occupancy", "94%", "148 / 158 homes"], ["Engagement", "81%", "Last 30 days"]] },
    config: { stats: [["Society name", "Greenwood Residency", "MH/2011/00842", "flat"], ["Buildings", "4", "A, B, C, D", "flat"], ["Total units", "158", "Monthly billing", "flat"], ["Late fee", "2%", "After 10 days", "flat"]], title: "Society configuration", icon: Settings2, rows: [["Society name", "Greenwood Residency", "CHS"], ["Registration no.", "MH/2011/00842", "Verified"], ["Billing cycle", "Monthly", "1st of month"], ["Rate", "₹4.25 / sq.ft", "Current"]] },
    roles: { stats: [["Active roles", "8", "permission-scoped", "flat"], ["Admin users", "2", "full access", "flat"], ["Resident users", "148", "all homes", "up"], ["Pending invites", "3", "review needed", "down"]], title: "Access map", icon: ShieldCheck, rows: [["Admin", "Full access", "2 users"], ["Committee", "Finance + notices", "6 users"], ["Resident", "Own home + requests", "148 users"], ["Security", "Gate activity", "4 users"]] },
    migration: { stats: [["Imported residents", "154", "3 warnings", "up"], ["Duplicate records", "1", "needs review", "down"], ["Last import", "July 18", "CSV · 10:42 AM", "flat"], ["Data health", "98%", "ready to use", "up"]], title: "Import history", icon: Upload, rows: [["Residents July 2026", "CSV", "154 records"], ["Payment register", "XLSX", "158 records"], ["Visitor archive", "CSV", "2,840 records"]] }
  };
  const g = generic[mod] ?? generic.config;
  return <div className="space-y-12"><Stats items={g.stats} /><Section title={g.title} action={mod === "migration" ? "Import file" : mod === "config" ? "Edit setup" : mod === "roles" ? "Manage access" : "View report"} icon={g.icon}><div className="divide-y divide-border rounded-xl border border-border">{g.rows.map(x => <div key={x[0]} className="flex flex-wrap items-center justify-between gap-4 px-4 py-4 hover:bg-surface-2/60 sm:px-5"><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-surface-2 text-primary"><FileText size={15} /></span><div><div className="font-semibold">{x[0]}</div><div className="mt-1 text-sm text-ink-faint">{x[1]}</div></div></div><span className="text-sm font-semibold text-ink-soft">{x[2]}</span></div>)}</div></Section>{mod === "migration" && <Section title="Drop a file to import" icon={Upload}><div className="rounded-2xl border-2 border-dashed border-border bg-surface-2 px-6 py-12 text-center transition hover:border-primary"><Upload className="mx-auto text-primary" size={25} /><div className="mt-3 font-semibold">Residents, payments, complaints</div><div className="mt-1 text-sm text-ink-faint">CSV or XLSX, up to 20 MB</div><button className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-full bg-primary px-5 text-sm font-semibold text-[var(--bg)]"><Upload size={16} /> Choose file</button></div></Section>}</div>;
}
function Shell() { const params = useSearchParams(); const role = (params.get("role") as RoleKey) || "resident"; const [active, setActive] = useState<ModuleKey>("dashboard"); const [navOpen, setNavOpen] = useState(false); const R = ROLES[role]; const hr = new Date().getHours(); const greeting = hr < 12 ? "Good morning" : hr < 17 ? "Good afternoon" : "Good evening"; const titles: Record<ModuleKey, string> = { dashboard: `${greeting}, ${R.name.split(" ")[0]}`, residents: "Residents", billing: "Maintenance & Billing", finance: "Financials", visitors: "Security & Visitors", complaints: "Complaints & Service Requests", comms: "Notices & Events", reports: "Reports", config: "Society Setup", roles: "Roles & Permissions", migration: "Data Migration" }; return <div className="lg:grid lg:grid-cols-[278px_1fr]"><Sidebar role={role} active={active} onNavigate={setActive} open={navOpen} onClose={() => setNavOpen(false)} />{navOpen && <div onClick={() => setNavOpen(false)} className="fixed inset-0 z-[55] bg-black/40 lg:hidden" />}<div className="h-screen overflow-y-auto"><header className="sticky top-0 z-40 flex min-h-[76px] items-center gap-3 border-b border-border bg-bg/90 px-4 backdrop-blur sm:px-8"><button onClick={() => setNavOpen(true)} className="grid h-10 w-10 place-items-center rounded-full text-ink-soft hover:bg-surface-2 lg:hidden"><Menu size={20} /></button><div className="relative w-full max-w-[430px]"><Search size={17} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-ink-faint" /><input aria-label="Search" placeholder="Search residents, invoices, notices..." className="h-11 w-full rounded-full border border-border bg-surface pl-10 pr-4 text-sm outline-none placeholder:text-ink-faint" /></div><div className="ml-auto flex items-center gap-2"><button className="hidden h-10 items-center gap-2 rounded-full border border-border px-4 text-sm font-semibold text-ink-soft hover:bg-surface-2 sm:flex"><Plus size={16} /> New</button><ThemeToggle /><button aria-label="Notifications" className="grid h-10 w-10 place-items-center rounded-full text-ink-soft hover:bg-surface-2"><Bell size={18} /></button><span className="grid h-9 w-9 place-items-center rounded-full bg-primary-tint text-xs font-bold text-primary-strong">{R.initials}</span></div></header><main className="mx-auto max-w-[1440px] p-5 sm:p-8 lg:p-10"><motion.div key={active} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .4, ease: [.16, 1, .3, 1] }}><div className="mb-10 flex flex-wrap items-end justify-between gap-4"><div><div className="mb-3 text-xs font-bold uppercase tracking-[.14em] text-primary-strong">Greenwood Residency · July 2026</div><h1 className="font-serif text-4xl font-semibold tracking-tight sm:text-5xl">{titles[active]}</h1></div><div className="text-right text-sm text-ink-faint">Sunday<br /><span className="font-semibold text-ink">19 July 2026</span></div></div><ModuleView mod={active} /></motion.div></main></div></div>; }
export default function Dashboard() { return <Suspense><Shell /></Suspense>; }
