"use client";
import { useSearchParams } from "next/navigation";
import { useState, Suspense } from "react";
import { motion } from "framer-motion";
import { Bell, Menu, Search, Plus } from "lucide-react";
import Sidebar from "@/components/Sidebar";
import ThemeToggle from "@/components/ThemeToggle";
import Kpi from "@/components/Kpi";
import { ROLES, type RoleKey, type ModuleKey } from "@/lib/data";
const notices=[['Annual General Meeting','20 July, 6 PM · Clubhouse','Notice','2h ago'],['Water supply suspended','11 AM–2 PM today','Emergency','5h ago'],['Independence Day celebration','15 August · Central lawn','Event','1d ago']];
const residents=[['Rahul Shah','A-1204','Owner','Active','Nil'],['Ramesh Iyer','A-0501','Owner','Active','Nil'],['Sana Qureshi','B-0710','Tenant','Active','₹4,500'],['George Thomas','C-1108','Tenant','Notice','₹9,000']];
const bills=[['INV-2607-1204','A-1204','₹6,800','Paid'],['INV-2607-0710','B-0710','₹4,500','Overdue'],['INV-2607-1108','C-1108','₹9,000','Overdue'],['INV-2607-1101','D-1101','₹6,800','Pending']];
const complaints=[['Water leakage in A-wing parking','Plumbing','High','Open'],['Lift 2 tripping in B-wing','Electrical','Urgent','Open'],['Garbage not collected C-wing','Housekeeping','Medium','In progress'],['Garden lights out near clubhouse','Common Area','Medium','Resolved']];
function Badge({children}:{children:string}){const s=children.toLowerCase();const c=s.includes('paid')||s.includes('active')||s.includes('resolved')?'text-[var(--good)] bg-emerald-500/10':s.includes('overdue')||s.includes('urgent')||s.includes('notice')?'text-[var(--bad)] bg-red-500/10':s.includes('high')||s.includes('progress')?'text-amber-600 bg-amber-500/10':'text-ink-soft bg-surface-2';return <span className={`inline-flex rounded-full px-2.5 py-1 text-[.7rem] font-bold ${c}`}>{children}</span>}
function Panel({title,action,children}:{title:string;action?:string;children:React.ReactNode}){return <section className="border-t border-border pt-4"><div className="mb-4 flex items-center justify-between"><h2 className="text-[.75rem] font-bold uppercase tracking-[.12em] text-ink-faint">{title}</h2>{action&&<button className="text-sm font-semibold text-primary-strong hover:underline">{action}</button>}</div>{children}</section>}
function StatRow({items}:{items:[string,string,string,('up'|'down'|'flat')][]}){return <div className="grid grid-cols-2 gap-x-6 gap-y-6 xl:grid-cols-4">{items.map((x,i)=><Kpi key={x[0]} label={x[0]} value={x[1]} delta={x[2]} dir={x[3]} index={i}/>)}</div>}
function Table({kind}:{kind:'residents'|'billing'}){const data=kind==='residents'?residents:bills;return <div className="overflow-x-auto"><table className="w-full min-w-[600px] text-left"><thead><tr className="border-b border-border text-[.68rem] font-bold uppercase tracking-[.1em] text-ink-faint">{(kind==='residents'?['Resident','Flat','Type','Status','Outstanding']:['Invoice','Flat','Amount','Status']).map(x=><th key={x} className="px-3 pb-3">{x}</th>)}</tr></thead><tbody>{data.map((row,i)=><tr key={i} className="border-b border-border/70 last:border-0 hover:bg-surface-2/70">{row.map((x,j)=><td key={j} className={`px-3 py-3 text-sm ${j===0?'font-semibold':''} ${x.startsWith('₹')?'tabular-nums':''}`}>{((kind==='residents'&&j===2)||(kind==='residents'&&j===3)||(kind==='billing'&&j===3))?<Badge>{x}</Badge>:x}</td>)}</tr>)}</tbody></table></div>}
function Overview({mod}:{mod:ModuleKey}){if(mod==='dashboard')return <div className="space-y-10"><StatRow items={[["Collection this cycle","₹2.84L","92% collected","up"],["Outstanding dues","₹1.57L","6 flats pending","down"],["Open complaints","8","2 urgent","flat"],["Occupancy","94%","148 / 158 flats","up"]]}/><Panel title="Latest notices" action="View all"><div className="divide-y divide-border border-y border-border">{notices.map(x=><div key={x[0]} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><div className="font-semibold">{x[0]}</div><div className="mt-1 text-sm text-ink-faint">{x[2]} · {x[1]}</div></div><span className="text-xs text-ink-faint">{x[3]}</span></div>)}</div></Panel></div>;
if(mod==='residents')return <div className="space-y-10"><StatRow items={[["Total flats","158","4 blocks A–D","flat"],["Owners","112","71% of units","flat"],["Tenants","36","KYC verified","up"],["Vacant","10","6% of units","down"]]}/><Panel title="Resident directory" action="Export"><Table kind="residents"/></Panel></div>;
if(mod==='billing')return <div className="space-y-10"><StatRow items={[["Billed in July","₹3.09L","158 invoices","flat"],["Collected","₹2.84L","92%","up"],["Pending","₹15.7K","3 flats","flat"],["Overdue + late fee","₹13.5K","2 flats","down"]]}/><Panel title="Invoice register" action="Create invoice"><Table kind="billing"/></Panel></div>;
if(mod==='complaints')return <div className="space-y-10"><StatRow items={[["Open","2","1 urgent","flat"],["In progress","1","within SLA","flat"],["Resolved in 7d","5","avg 1.2 days","up"],["Satisfaction","4.6","22 ratings","up"]]}/><Panel title="Service queue" action="New request"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{['Open','In progress','Resolved','Closed'].map(status=><div key={status} className="rounded-2xl bg-surface-2 p-3"><div className="mb-3 px-1 text-sm font-semibold">{status} <span className="ml-1 text-ink-faint">{complaints.filter(x=>x[3]===status).length}</span></div>{complaints.filter(x=>x[3]===status).map((x,i)=><div key={x[0]} className="mb-2 rounded-xl border border-border bg-surface p-3"><div className="text-[.68rem] font-bold uppercase tracking-[.08em] text-ink-faint">{x[1]}</div><div className="my-2 text-sm font-semibold leading-5">{x[0]}</div><div className="flex items-center gap-2"><Badge>{x[2]}</Badge><span className="text-xs text-ink-faint">CMP-{341-i}</span></div></div>)}</div>)}</div></Panel></div>;
if(mod==='visitors')return <div className="space-y-10"><StatRow items={[["Entries today","42","+6","up"],["Inside now","12","3 deliveries","flat"],["Deliveries","18","peak 6–8 PM","up"],["Awaiting approval","1","B-0710","flat"]]}/><Panel title="Gate activity" action="Log visitor"><div className="divide-y divide-border border-y border-border">{[['Amazon Delivery','A-1204','6:42 PM','Inside'],['Dr. S. Kapoor','C-0304','6:20 PM','Inside'],['Uber MH04 KT8890','B-0902','6:05 PM','Exited'],['Unknown Guest','B-0710','6:50 PM','Waiting']].map(x=><div key={x[0]} className="flex items-center justify-between gap-4 py-4"><div><div className="font-semibold">{x[0]}</div><div className="mt-1 text-sm text-ink-faint">{x[1]} · {x[2]}</div></div><Badge>{x[3]}</Badge></div>)}</div></Panel></div>;
const generic:Record<string,[string,string,string,('up'|'down'|'flat')][]>={comms:[["Active notices","5","4 unread avg","flat"],["Upcoming events","2","64 RSVPs","up"],["Delivery rate","98%","in-app + email + SMS","up"],["Read rate","81%","last 30 days","up"]],finance:[["Income FY26","₹34.2L","+8% YoY","up"],["Expenses FY26","₹28.8L","+5% YoY","down"],["Net surplus","₹5.4L","healthy","up"],["Reserve fund","₹18.4L","corpus intact","up"]],reports:[["Collection efficiency","92%","healthy","up"],["Complaint SLA","88%","on track","up"],["Occupancy","94%","148 / 158","up"],["Engagement","81%","last 30 days","up"]],config:[["Society name","Greenwood Residency","MH/2011/00842","flat"],["Buildings","4","A, B, C, D","flat"],["Total units","158","Monthly billing","flat"],["Late fee","2%","After 10 days","flat"]],roles:[["Active roles","8","permission-scoped","flat"],["Admin users","2","full access","flat"],["Resident users","148","all homes","up"],["Pending invites","3","review needed","down"]],migration:[["Imported residents","154","3 warnings","up"],["Duplicate records","1","needs review","down"],["Last import","July 18","CSV · 10:42 AM","flat"],["Data health","98%","ready to use","up"]]};return <div className="space-y-10"><StatRow items={generic[mod]??generic.config}/><Panel title={mod==='config'?'Society configuration':'Overview'}><div className="divide-y divide-border border-y border-border">{(generic[mod]??generic.config).map(x=><div key={x[0]} className="flex justify-between gap-4 py-4 text-sm"><span className="text-ink-soft">{x[0]}</span><span className="font-semibold">{x[1]}</span></div>)}</div></Panel></div>}
function Shell(){const params=useSearchParams();const role=(params.get('role') as RoleKey)||'resident';const [active,setActive]=useState<ModuleKey>('dashboard');const [navOpen,setNavOpen]=useState(false);const R=ROLES[role];const hr=new Date().getHours();const greeting=hr<12?'Good morning':hr<17?'Good afternoon':'Good evening';const titles:Record<ModuleKey,string>={dashboard:`${greeting}, ${R.name.split(' ')[0]}`,residents:'Residents',billing:'Maintenance & Billing',finance:'Financials',visitors:'Security & Visitors',complaints:'Complaints & Service Requests',comms:'Notices & Events',reports:'Reports',config:'Society Setup',roles:'Roles & Permissions',migration:'Data Migration'};return <div className="lg:grid lg:grid-cols-[278px_1fr]"><Sidebar role={role} active={active} onNavigate={setActive} open={navOpen} onClose={()=>setNavOpen(false)}/>{navOpen&&<div onClick={()=>setNavOpen(false)} className="fixed inset-0 z-[55] bg-black/40 lg:hidden"/>}<div className="h-screen overflow-y-auto"><header className="sticky top-0 z-40 flex min-h-[76px] items-center gap-3 border-b border-border bg-bg/90 px-4 backdrop-blur sm:px-8"><button onClick={()=>setNavOpen(true)} className="grid h-10 w-10 place-items-center rounded-full text-ink-soft hover:bg-surface-2 lg:hidden"><Menu size={20}/></button><div className="relative w-full max-w-[430px]"><Search size={17} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-ink-faint"/><input placeholder="Search residents, invoices, notices..." className="h-11 w-full rounded-full border border-border bg-surface pl-10 pr-4 text-sm outline-none placeholder:text-ink-faint"/></div><div className="ml-auto flex items-center gap-2"><button className="hidden h-10 items-center gap-2 rounded-full border border-border px-4 text-sm font-semibold text-ink-soft hover:bg-surface-2 sm:flex"><Plus size={16}/> New</button><ThemeToggle/><button className="grid h-10 w-10 place-items-center rounded-full text-ink-soft hover:bg-surface-2"><Bell size={18}/></button><span className="grid h-9 w-9 place-items-center rounded-full bg-primary-tint text-xs font-bold text-primary-strong">{R.initials}</span></div></header><main className="mx-auto max-w-[1440px] p-5 sm:p-8 lg:p-10"><motion.div key={active} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{duration:.4,ease:[.16,1,.3,1]}}><div className="mb-10 flex flex-wrap items-end justify-between gap-4"><div><div className="mb-3 text-xs font-bold uppercase tracking-[.14em] text-primary-strong">Greenwood Residency · July 2026</div><h1 className="font-serif text-4xl font-semibold tracking-tight sm:text-5xl">{titles[active]}</h1></div><div className="text-right text-sm text-ink-faint">Sunday<br/><span className="font-semibold text-ink">19 July 2026</span></div></div><Overview mod={active}/></motion.div></main></div></div>}
export default function Dashboard(){return <Suspense><Shell/></Suspense>}
