"use client";
import { motion } from "framer-motion";
import { useRouter } from "next/navigation";
import * as Icons from "lucide-react";
import { MODULES, ACCESS, GROUP_ORDER, ROLES, type RoleKey, type ModuleKey } from "@/lib/data";
export default function Sidebar({role,active,onNavigate,open,onClose}:{role:RoleKey;active:ModuleKey;onNavigate:(m:ModuleKey)=>void;open:boolean;onClose:()=>void}) {
  const R=ROLES[role]; const router=useRouter(); let i=0;
  return <aside className={`fixed inset-y-0 left-0 z-[60] flex w-[278px] flex-col border-r border-border bg-surface transition-transform duration-300 lg:static lg:translate-x-0 ${open?"translate-x-0 shadow-2xl":"-translate-x-full"}`}>
    <div className="border-b border-border px-6 pb-6 pt-7"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-[13px] bg-primary text-[var(--bg)]"><Icons.Building2 size={20}/></span><div><div className="font-serif text-xl font-semibold leading-none">My Society</div><div className="mt-1 text-xs text-ink-faint">Greenwood Residency</div></div></div><button onClick={onClose} className="grid h-8 w-8 place-items-center rounded-full text-ink-soft hover:bg-surface-2 lg:hidden"><Icons.X size={18}/></button></div></div>
    <nav className="flex-1 overflow-y-auto px-4 py-5">{GROUP_ORDER.map(group=>{const mods=(Object.keys(MODULES) as ModuleKey[]).filter(m=>MODULES[m].group===group&&ACCESS[m].includes(role));if(!mods.length)return null;return <div key={group} className="mb-5"><div className="px-3 pb-2 text-[.68rem] font-bold uppercase tracking-[.14em] text-ink-faint">{group}</div>{mods.map(m=>{const Icon=(Icons as any)[MODULES[m].icon]??Icons.Circle;const on=active===m;return <motion.button key={m} initial={{opacity:0,x:-8}} animate={{opacity:1,x:0}} transition={{delay:i++*.025,ease:[.16,1,.3,1]}} onClick={()=>{onNavigate(m);onClose()}} className={`flex min-h-11 w-full items-center gap-3 rounded-[11px] px-3 text-left text-[.9rem] font-medium transition ${on?"bg-primary text-[var(--bg)] shadow-[0_8px_20px_-12px_var(--primary)]":"text-ink-soft hover:bg-surface-2 hover:text-ink"}`}><Icon size={17}/><span>{MODULES[m].label}</span>{on&&<Icons.ChevronRight size={15} className="ml-auto opacity-70"/>}</motion.button>})}</div>})}</nav>
    <div className="border-t border-border p-4"><div className="flex items-center gap-3 rounded-xl bg-surface-2 px-3 py-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-primary-tint text-xs font-bold text-primary-strong">{R.initials}</span><div className="min-w-0"><b className="block truncate text-[.85rem]">{R.name}</b><span className="text-xs text-ink-faint">{R.label} · {R.flat}</span></div></div><button onClick={()=>router.push('/login')} className="mt-3 flex min-h-11 w-full items-center gap-3 rounded-[11px] px-3 text-left text-[.88rem] font-medium text-ink-soft hover:bg-red-500/10 hover:text-[var(--bad)]"><Icons.LogOut size={17}/> Log out</button></div>
  </aside>;
}
