"use client";
import { useRouter } from "next/navigation";
import { motion } from "framer-motion";
import { ArrowUpRight, Building2, Check, ChevronRight, CircleDollarSign, Menu, ShieldCheck, Sparkles, UsersRound, Wrench } from "lucide-react";
import ThemeToggle from "@/components/ThemeToggle";
const features=[{icon:CircleDollarSign,title:"Money, without the mystery",text:"Invoices, collections and reserves in one readable ledger."},{icon:Wrench,title:"Issues get a proper owner",text:"Track every complaint from first note to final fix."},{icon:ShieldCheck,title:"Access that makes sense",text:"Every role sees the work they actually need."}];
export default function Home(){const router=useRouter();return <main className="min-h-screen overflow-hidden bg-bg">
  <nav className="mx-auto flex max-w-[1240px] items-center justify-between px-6 py-6 lg:px-10"><div className="flex items-center gap-3 font-serif text-xl font-semibold"><span className="grid h-10 w-10 place-items-center rounded-[13px] bg-primary text-[var(--bg)]"><Building2 size={20}/></span>My Society</div><div className="flex items-center gap-2"><a href="#why" className="hidden rounded-full px-4 py-2 text-sm text-ink-soft hover:bg-surface-2 sm:block">Why it works</a><ThemeToggle/><button onClick={()=>router.push('/login')} className="rounded-full bg-primary px-5 py-2.5 text-sm font-semibold text-[var(--bg)] transition hover:-translate-y-0.5">Sign in</button></div></nav>
  <section className="mx-auto grid max-w-[1240px] items-center gap-14 px-6 pb-20 pt-12 lg:grid-cols-[.9fr_1.1fr] lg:px-10 lg:pb-28 lg:pt-20"><div className="max-w-[590px]"><motion.div initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="mb-6 inline-flex items-center gap-2 rounded-full border border-border bg-surface px-3.5 py-2 text-xs font-bold uppercase tracking-[.1em] text-primary-strong"><Sparkles size={14}/> Built for real communities</motion.div><motion.h1 initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{delay:.08}} className="font-serif text-[clamp(3.3rem,7vw,6.4rem)] font-semibold leading-[.92] tracking-[-.055em]">A calmer way to run your <em className="text-primary">society.</em></motion.h1><motion.p initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{delay:.16}} className="mt-7 max-w-[48ch] text-lg leading-8 text-ink-soft">Maintenance, visitors, complaints and governance in one place. Less chasing. More clarity for every resident and committee.</motion.p><motion.div initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{delay:.24}} className="mt-9 flex flex-wrap items-center gap-3"><button onClick={()=>router.push('/login')} className="inline-flex min-h-12 items-center gap-2 rounded-full bg-primary px-6 font-semibold text-[var(--bg)] transition hover:-translate-y-1">Open the workspace <ArrowUpRight size={18}/></button><a href="#why" className="inline-flex min-h-12 items-center gap-2 rounded-full border border-border px-5 font-semibold text-ink-soft hover:bg-surface-2">See how it works <ChevronRight size={17}/></a></motion.div><div className="mt-12 flex flex-wrap gap-x-9 gap-y-3 text-sm text-ink-faint"><span><b className="text-ink">158</b> homes</span><span><b className="text-ink">92%</b> collected</span><span><b className="text-ink">8</b> roles</span></div></div>
    <motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} transition={{duration:.7,ease:[.16,1,.3,1]}} className="relative min-h-[460px] rounded-[32px] bg-primary p-5 text-[var(--bg)] shadow-2xl shadow-primary/15 sm:p-8"><div className="absolute right-8 top-8 h-28 w-28 rounded-full border border-[color:var(--bg)]/20"/><div className="absolute bottom-9 left-8 h-16 w-16 rounded-full border border-[color:var(--bg)]/20"/><div className="relative flex h-full min-h-[400px] flex-col justify-between"><div className="flex items-center justify-between text-sm"><span className="flex items-center gap-2 font-semibold"><UsersRound size={17}/> Greenwood Residency</span><span className="rounded-full bg-[color:var(--bg)]/15 px-3 py-1.5 text-xs">Live overview</span></div><div className="relative mx-auto w-full max-w-[510px] rounded-[24px] bg-[color:var(--bg)] p-5 text-ink shadow-2xl sm:p-7"><div className="flex items-start justify-between"><div><div className="text-xs font-bold uppercase tracking-[.12em] text-ink-faint">Sunday, 19 July</div><h2 className="mt-2 font-serif text-3xl font-semibold">Good evening, Rahul</h2></div><span className="grid h-10 w-10 place-items-center rounded-full bg-primary-tint text-xs font-bold text-primary-strong">RS</span></div><div className="mt-8 grid grid-cols-2 gap-x-6 gap-y-7 sm:grid-cols-4">{[["Collection","₹2.84L","92%"],["Outstanding","₹1.57L","6 flats"],["Complaints","8","2 urgent"],["Occupancy","94%","148 / 158"]].map(([a,b,c])=><div key={a} className="border-t border-border pt-3"><div className="text-[.68rem] font-bold uppercase tracking-[.1em] text-ink-faint">{a}</div><div className="mt-2 text-xl font-bold tabular-nums">{b}</div><div className="mt-1 text-xs text-primary-strong">{c}</div></div>)}</div><div className="mt-8 border-t border-border pt-4"><div className="flex items-center justify-between text-sm font-semibold"><span>Latest notice</span><span className="text-xs text-ink-faint">2h ago</span></div><p className="mt-2 text-sm text-ink-soft">Annual General Meeting, 20 July, 6 PM Clubhouse</p></div></div><div className="flex items-end justify-between"><div><div className="font-serif text-2xl">Everything in view.</div><div className="mt-1 text-sm opacity-75">The boring stuff, finally made simple.</div></div><div className="grid h-12 w-12 place-items-center rounded-full border border-[color:var(--bg)]/30"><Check size={20}/></div></div></div></motion.div>
  </section>
  <section id="why" className="border-t border-border bg-surface"><div className="mx-auto max-w-[1240px] px-6 py-20 lg:px-10"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><div className="text-xs font-bold uppercase tracking-[.14em] text-primary-strong">Why it works</div><h2 className="mt-4 max-w-[12ch] font-serif text-4xl font-semibold leading-tight sm:text-5xl">The right amount of software.</h2></div><div className="grid gap-9 sm:grid-cols-3">{features.map(({icon:Icon,title,text})=><div key={title} className="border-t border-border pt-4"><Icon size={20} className="text-primary"/><h3 className="mt-5 text-base font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-ink-soft">{text}</p></div>)}</div></div></div></section>
</main>}
